### ISSUE TITLE
great job!

### ISSUE THREAD

**Issue by dengzuxuan** [SheepTAO/dpeeg#1]
perfect job,may I use **dpeeg** in my paper code? could you tell me which paper I should cite, thank you very much.

**Comment by SheepTAO** [comment]
Thank you for your interest in **dpeeg**! Currently, **dpeeg** is still under development, and I do not have a specific citation format yet. However, you can refer to a paper of mine that has used this package for citation, which can be found https://github.com/SheepTAO/MSVTNet. I will provide more information on how to correctly cite the package in the future.

**Comment by SheepTAO** [comment]
> perfect job,may I use **dpeeg** in my paper code? could you tell me which paper I should cite, thank you very much.

Thank you for your interest in dpeeg! Currently, dpeeg is still under development, and I do not have a specific citation format yet. However, you can refer to a paper of mine that has used this package for citation, which can be found https://github.com/SheepTAO/MSVTNet. I will provide more information on how to correctly cite the package in the future.
